### ISSUE TITLE
Move Configuration Provider from Kernel

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/carbon-config#1]
In Carbon 5.2.0-m3, configuration provider and org.wso2.carbon.extensions.configuration.maven.plugin resides in kernel and supports only OSGi model. This needs to be moved to this repo and in-addition to OSGi support, it should also provide support for non-OSGi. 

deployment.yaml should be runtime specific, i.e., \<CARBON HOME\>/wso2/\<runtime\>/config

**Comment by imesh** [comment]
We have now moved the configuration provider from the carbon-kernel repository to the master branch of this repository with commit history.
