### ISSUE TITLE
Project Dependencies and Project are not picked in Carbon Configuration Maven Plugin

### ISSUE THREAD

**Issue by vidurananayakkara** [wso2/carbon-config#14]
Carbon configuration maven plugin does not pick the project dependencies and the project when building the configuration. This will cause the plugin not to build the configuration when the specified configuration class is within the project or in a specified dependency

**Example:**

When the plugin is specified as mentioned below

```
           <plugin>
                <groupId>org.wso2.carbon.config</groupId>
                <artifactId>org.wso2.carbon.config.configuration.maven.plugin</artifactId>
                <version>${carbon.configuration.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>create-doc</goal>
                        </goals>
                        <phase>compile</phase>
                    </execution>
                </executions>
                <configuration>
                    <configclasses>
                        <configclass>org.wso2.carbon.kernel.config.model.CarbonConfiguration</configclass>
                    </configclasses>
                </configuration>
            </plugin>
```

and dependencies as mentioned below:

```
    <dependencies>
        <dependency>
            <groupId>org.wso2.carbon</groupId>
            <artifactId>org.wso2.carbon.core</artifactId>
        </dependency>
    </dependencies>
```

Maven configuration plugin throws a "[NoClassDefFoundError](https://docs.oracle.com/javase/7/docs/api/java/lang/NoClassDefFoundError.html)" stating that the org.wso2.carbon.kernel.config.model.CarbonConfiguration (specified configuration classes) definition is not found. This happens because the org.wso2.carbon.core is not in the class realm. Ideally, dependencies should be added to the class realm so that users can specify the dependencies for which they want to run the config plugin

**Comment by Niranjan-K** [comment]
@vidurananayakkara : Sorry but can you explain this with an example.
