### ISSUE TITLE
The config provide plugin need to copy the config-docs/ folder into the target/classes/ folder

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/carbon-config#2]
Moving Issue from Kernel, https://github.com/wso2/carbon-kernel/issues/1315

This is regarding the the maven plugin - 'org.wso2.carbon: org.wso2.carbon.extensions.configuration.maven.plugin'

At the moment, the generated config-docs is copied directly inside target/ folder. We need to add the config-docs inside target/classes/ folder by default. The rationale is, the contents under src/main/resources already goes to target/classes/ folder. The config-docs is another resource file that should be packed within the bundle itself.

Going forward, we could also provide an optional config to provide the outputDirectory. Still, the default should be to go inside target/classes.

**Comment by daneshk** [comment]
in maven-plugin (org.wso2.carbon: org.wso2.carbon.extensions.configuration.maven.plugin), we are saving generated docs(config-docs directory) inside target/classes/ folder in the component. This plugin is to use in component to generate config-docs and it not handles config-doc location in feature.

In the feature, we get the config-docs directory from the component jar and add it to the feature zip file using maven-dependency-plugin, where we unpack the component jar file are put it inside target/ folder in the feature. We add all the docs inside target/config-docs to the feature. This path can be change in the feature pom as required.

**Comment by daneshk** [comment]
Closing the issue referring to the above comment.
