### ISSUE TITLE
Place holders are not replacing when hard-code the values are in the bean class

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/carbon-config#3]
Move issue from Kernel, https://github.com/wso2/carbon-kernel/issues/1316

Replace only when the namespace presents in the deployment.yaml.
https://github.com/wso2/carbon-kernel/blob/master/core/src/main/java/org/wso2/carbon/kernel/internal/configprovider/ConfigProviderImpl.java#L87

**Comment by daneshk** [comment]
one option is to provide util method to use it in the bean class constructor. So whenever we have a variable referring to system or environment variable, need to use this method to assign expression to the variable. some thing like,

    public DeploymentConfiguration() {
        repositoryLocation = ConfigProviderUtils.substituteVariables("${carbon.home}/deployment/");
    }

substituteVariables method handles the logic to replace expression with system values at runtime.

**Comment by daneshk** [comment]
Suggested solution has already implemented in latest released version. hence closing the issue.
