### ISSUE TITLE
Sys value does not work if set to default value in the Bean class

### ISSUE THREAD

**Issue by Niranjan-K** [wso2/carbon-config#4]
If the default value in the Bean class is set using the environment, say "${sys:carbon.home}, then it does not work. For example in carbon-deployment, the repositoryLocation is obtained from the deployment.yaml. If the default value is set as "${sys:carbon.home}/deployment/" then it does not work.

**Comment by daneshk** [comment]
This issue is duplicate with wso2/carbon-config#3. hence closing this issue.
