### ISSUE TITLE
Implement configuration lookup from environment variable

### ISSUE THREAD

**Issue by daneshk** [wso2/carbon-config#48]
From the current approach, when we need to read the configurations from environment variables, we need to specifically mention in the deployment.yaml file as
> gateWayEndpoint: ${env:gateWayEndpoint}

But in a containerized environment, changing configuration file is harder, because we cannot maintain a single Container Image for different deployments, and manipulate the Container runtimes via environment variables.

From the suggested approach, read priority will be,
1. Read configurations from environment variables. environment variable should define in a certain format like
> PREFIX_wso2.NAMESPACE_CONFIGKEY="value", PREFIX_wso2.NAMESPACE_CONFIGPARENT_CONFIG2="value2"
2. Read the deployment.yaml file.
3. Get default values from the bean class.

**Comment by imesh** [comment]
When naming environment variables, it might be better if can allow developers to specify custom property names while generating env name automatically using the namespace and property name.
