### ISSUE TITLE
Unable to use "$" character in password, with ciphertool enabled

### ISSUE THREAD

**Issue by udarakr** [wso2/carbon-config#69]
**Description:**
Unable to use "$" character in password, with ciphertool enabled

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by daneshk** [comment]
Closing this issue, since fix it already merged to master
